config/routes.rb
Diningin::Application.routes.draw do
  match '/checkuser', :controller => 'users', :action => 'checkuser', :method => :get
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base

validates_presence_of :username
validates_presence_of :password
validates_presence_of :email

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end


  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end



  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
	
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end


  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end



  # POST /users
  # POST /users.xml
  def create
	  @user = User.new(params[:user])
	  @user.created_by = 15
	  
	  @user.save
	   flash[:message] ="User created successfully!"
	  redirect_to "/users"
	  
	  # have to put the code in case of error
	  
  end


  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])
    @user.firstname = @user.firstname.strip
    
	@user.update_attributes(params[:user])
   
    flash[:message] ="User updated successfully!"

	redirect_to "/users"
	
	# have to put the code in case of error
	
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
  
  
  
  # in users_controller.rb
def check_email
@user = User.find_by_email(params[:user][:email])
 
respond_to do |format|
format.json { render :json => !@user }
end
end


def checkuser
  @user = User.find_by_username(params[:user_username])
  if @user
    render :text => true, :layout => false
  elsif params[:user_username].blank?
    render :text => true, :layout => false
  else
    render :text => false, :layout => false
  end
end



  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />



<title>Dining In Admin</title>



<%= stylesheet_link_tag 'styles.css' %>
<%= stylesheet_link_tag 'ddsmoothmenu.css' %>
<%= stylesheet_link_tag 'ddsmoothmenu-v.css' %>



<script type="text/javascript" src="../../javascripts/ddsmoothmenu.js"></script>
<%= javascript_include_tag 'jquery-1.5.2.js', 'jquery.validate.js', 'application' %>



<script type="text/javascript">

ddsmoothmenu.init({
	mainmenuid: "smoothmenu1", //menu DIV id
	orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
	classname: 'ddsmoothmenu', //class added to menu's outer DIV
	//customtheme: ["#1c5a80", "#18374a"],
	contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
})


// Sets the form focus to the first element found in forms[0] that
// is a textfield or text area
function setFocus() {
// Bail if no form on page
if (document.forms[0] == null) return;

// Iterate though elements
for (var i = 0; i < document.forms[0].elements.length; i++) {
  e = document.forms[0].elements[i];
  if ((e.type == "text") || (e.type == "textarea")) {
    e.focus();
    break;
  }
}
}

</script>  

<body onload="setFocus()">


<style type="text/css">
.grey-bg tr td table tr td table {
	font-weight: bold;
}
</style>
</head>

<body>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td class="h_color">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="15%" align="left" id="logo" ><a href="index.html"><img src="../../images/logo.gif" /></a></td>
        <td align="right" width="35%"><h1>Administrator</h1></td>
        <td width="50%" valign="top">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          
          <tr>
            <td height="30">&nbsp;</td>
          </tr>
          <tr>
            <td>
            <div id="top_menu">
                    <ul>
                        <li style="background-image:none;">Welcome Ram</li>
                        <li>You logged in as Super Admin</li>
                        <li><a href="#"><strong>Sign Out</strong></a></li>
                    </ul>
                </div>
			</td>
          </tr>
        </table></td>
      </tr>
      <tr><td height="2" bgcolor="#d15b28" colspan="3"></td></tr>
            
      <tr>
        <td colspan="3">
<div id="smoothmenu1" class="ddsmoothmenu">
<ul>
<li><a href="#" class="active" >User</a>
<ul>
<li><a href="../../users">Manage Users</a></li>
</ul>
</li>
<li><a href="menu.html">Maintain Restaurant Menu</a></li>
<li><a href="#">Maintain Restaurant</a></li>
<li><a href="#">News</a>
<ul>
<li><a href="#">Sub Item 2.1</a></li>
<li><a href="#">Folder 2.1</a>
<ul>
<li><a href="#">Sub Item 2.1.1</a></li>
<li><a href="#">Sub Item 2.1.2</a></li>
<li><a href="#">Folder 3.1.1</a>
<ul>
<li><a href="#">Sub Item 3.1.1.1</a></li>
<li><a href="#">Sub Item 3.1.1.2</a></li>
<li><a href="#">Sub Item 3.1.1.3</a></li>
<li><a href="#">Sub Item 3.1.1.4</a></li>
<li><a href="#">Sub Item 3.1.1.5</a></li>
</ul>
</li>
<li><a href="#">Sub Item 2.1.4</a></li>
</ul>
</li>
</ul>
</li>
<li><a href="#" style="border-right:none;">Newsletter</a></li>
</ul>
<br style="clear: left" />
</div>
      </tr>
    </table></td>
  </tr>
<tr>
<td height="100">

<%= yield %>

</td>
  </tr>
    <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
<td height="15"></td>
</tr>
</table>
</body>
</html>

app/views/users/changepassword.html.erb
<%= form_for(@user) do |f| %>
<%= javascript_include_tag 'jquery-1.5.2.js', 'jquery.validate.js', 'application' %>

<script type="text/javascript">

	$(document).ready(function () {
	$("#edit_user_1").validate({
	rules: {
	"user[username]": {required: true},
	"user[firstname]": {required: true},
	"user[lastname]": {required: true},
	"user[email]": {required: true, email: true},

	}
	});
	});


</script>


<div class="actions">

	
</div>

<table width="100%" border="0" cellspacing="0" cellpadding="6">

    <td colspan="4"><h2>Edit User</h2></td>
    </tr>
    <tr>
    <td align="right"class="brown_txt_m"><strong><span class="redstar">*</span> user name</strong></td>
    <td>:</td>
    <td colspan="2" align="left"><%= f.text_field :username, :class=>'textfield_b' %></td>
    </tr>
  <tr>
    <td width="22%" align="right" valign="middle" class="brown_txt_m"><strong><span class="redstar">*</span> first name</strong></td>
    <td width="2%">:</td>
    <td colspan="2" align="left"><%= f.text_field :firstname, :class=>'textfield_b' %></td>
    </tr>
  <tr>
    <td align="right"class="brown_txt_m"><strong><span class="redstar">*</span> last name</strong></td>
    <td>:</td>
    <td colspan="2" align="left"><%= f.text_field :lastname, :class=>'textfield_b' %></td>
    </tr>
  <tr>
    <td align="right"class="brown_txt_m"><strong><span class="redstar">*</span> email</strong></td>
    <td>:</td>
    <td colspan="2" align="left"><%= f.text_field :email, :class=>'textfield_b' %></td>
    </tr>
  
  
  
  <tr>
    <td align="right" class="brown_txt_m"><strong><span class="redstar">*</span> role</strong></td>
    <td>:</td>
    <td align="left">
    <%= f.select :role,options_for_select([['Administrator', 'Administrator'], ['Onboarder','Onboarder']]) %>   
    </tr>
   
  <tr>
    <td align="right" class="brown_txt_m"><strong><span class="redstar">*</span> status</strong></td>
    <td>:</td>
    <td align="left"><%= f.select :status,options_for_select([['active', 'active'], ['inactive','inactive']]) %>
    </td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td colspan="2" align="left"> <a class="squarebutton" href="/users" style="margin-left:6px;"  ><span>cancel</span></a> 
    <%= f.submit %>
    </td>

    </tr>
    
</table>    
<% end %>

app/views/users/edit.html.erb
<%= form_for(@user) do |f|  %>
<%= javascript_include_tag 'jquery-1.5.2.js', 'jquery.validate.js', 'application' %>

<script type="text/javascript">

	$(document).ready(function () {
	$("#edit_user_<%= @user.id %>").validate({
	rules: {
	"user[username]": {required: true},
	"user[firstname]": {required: true},
	"user[lastname]": {required: true},
	"user[email]": {required: true, email: true},

	}
	});
	});


</script>


<div class="actions">

	
</div>

<table width="100%" border="0" cellspacing="0" cellpadding="6">

    <td colspan="4"><h2>Edit User</h2></td>
    </tr>
    <tr>
    <td align="right"class="brown_txt_m"><strong><span class="redstar">*</span> user name</strong></td>
    <td>:</td>
    <td colspan="2" align="left"><%= f.text_field :username, :class=>'textfield_d' ,:disabled => true %></td>
    </tr>
  <tr>
    <td width="22%" align="right" valign="middle" class="brown_txt_m"><strong><span class="redstar">*</span> first name</strong></td>
    <td width="2%">:</td>
    <td colspan="2" align="left"><%= f.text_field :firstname, :class=>'textfield_b' %></td>
    </tr>
  <tr>
    <td align="right"class="brown_txt_m"><strong><span class="redstar">*</span> last name</strong></td>
    <td>:</td>
    <td colspan="2" align="left"><%= f.text_field :lastname, :class=>'textfield_b' %></td>
    </tr>
  <tr>
    <td align="right"class="brown_txt_m"><strong><span class="redstar">*</span> email</strong></td>
    <td>:</td>
    <td colspan="2" align="left"><%= f.text_field :email, :class=>'textfield_b' %></td>
    </tr>
  
  
  
  <tr>
    <td align="right" class="brown_txt_m"><strong><span class="redstar">*</span> role</strong></td>
    <td>:</td>
    <td align="left">
    
    <%= f.select :role,options_for_select([['Administrator', 'Administrator'], ['Onboarder','Onboarder']],@user.role) %>   
    </tr>
   
  <tr>
    <td align="right" class="brown_txt_m"><strong><span class="redstar">*</span> status</strong></td>
    <td>:</td>
    
    <td align="left"><%= f.select :status,options_for_select([['active', 'active'], ['inactive','inactive']],@user.status) %>
    </td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td colspan="2" align="left"> <a class="squarebutton" href="/users" style="margin-left:6px;"  ><span>cancel</span></a> 
    <%= f.submit %>
    </td>

    </tr>
    
</table>    
<% end %>

app/views/users/index.html.erb
<%= javascript_include_tag  'jquery.tablesorter.min.js', 'application' %>
<script type="text/javascript">

	$(document).ready(function()
	{
		$("#tbluser").tablesorter();
	}
	);


</script>
	
	

<h2>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td width="50%">Manage Users</td>
<td>
<table width="50%" border="0" align="right" cellpadding="0" cellspacing="0">
<tr>
<td valign="top"><a class="squarebutton" href="users/new" style="margin-left:10px;"  ><span>Add User</span></a> <a class="squarebutton" href="#" style="margin-left:10px;" ><span>Search</span></a> <a class="squarebutton" href="#" style="margin-left:10px;" ><span>Filter</span></a></td>
</tr>
<tr><td height="10"></td></tr>
<tr>
<td valign="top">
</td>
</tr>
</table>
</td>
</tr>
</table>
</h2>

</td>
</tr>
<tr><td height="10"></td></tr>          
          
<tr>

<td align="right"  valign="top" class="gry_clr" >
<table width="50%" border="0" align="right" cellpadding="0" cellspacing="0">
<tr><td height="10"></td></tr>
<tr>
<td colspan="2" valign="top">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td width="67%" class="brown_txt_m" align="right">
    	Stauts Filter by:
    </td>
    <td width="1%"></td>
    <td width="18%">
    	<select name="" id="" class="textselect_9">
<option selected="selected" >Active</option>
<option >Deactivated</option>
<option >Pending</option>
</select>
    </td>
    <td width="14%"></td>
  </tr>
</table>
</td>
</tr>
<tr><td height="5"></td></tr>

<tr>
  <td>
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">

<tr>
<td width="30%" align="right" valign="middle" class="brown_txt_m">Search by:</td>
<td width="1%"></td>
<td width="25%" valign="middle">
<select name="" id="" class="textselect_9">
<option selected="selected" >first Name</option>
<option >last Name</option>
<option >email</option>
<option >role</option>
<option >status</option>
</select>

</td>
<td width="23%" valign="middle"><input type="text" name="" class="textfield_s2" /></td>
<td width="10%" valign="top"><a class="squarebutton" href="#" style="margin-left:10px;" ><span>Go</span></a></td>
<td width="11%"></td>
</tr>


</table>

</td></tr>

</table>
</td>

</tr>
<tr>
	<td height="15"></td>
</tr>
<tr>
	<td height="20" align="center">

<% if flash[:message] %>
<%=flash[:message]%>
<%end%>
	</td>
	
</tr>
<tr>
	<td height="10"></td>
</tr>
	
<tr>
<td>
<table id="tbluser" width="95%" border="0" cellspacing="0" cellpadding="6" align="center" class="tablesorter">
	<thead>
 
  <tr>
	  
<td width="14%" class="gren_clr-t">User Name</td>
<td width="14%" class="gren_clr-t">First Name</td>
<td width="14%" class="gren_clr-t">Last Name</td>
<td width="18%" class="gren_clr-t">Email</td>
<td width="14%" class="gren_clr-t">Role</td>
<td width="10%" class="gren_clr-t">Status</td>
<td width="10%" class="gren_clr-t"></td>

</tr>
 </thead>


	<tbody>
		<% @users.each do |user| %>

		<tr>
			<td class="light_gr_clr-1">
				<%= user.username %>
			</td>
			<td class="light_gr_clr-1">
				<%= user.firstname %>
			</td>
			<td class="light_gr_clr-1">
				<%= user.lastname %>
			</td>
			<td class="light_gr_clr-1">
				<%= user.email %>
			</td>
			<td class="light_gr_clr-1">
				<%= user.role %>
			</td>
			<td class="light_gr_clr-1">
				<%= user.status %>
			</td>
			<td class="light_gr_clr-1">
				<%= link_to 'Edit', edit_user_path(user) %>
			</td>
		</tr>

		<% end %>
	</tbody>
</table>

app/views/users/new.html.erb
<%= javascript_include_tag 'jquery-1.5.2.js', 'jquery.validate.js', 'application' %>

<script type="text/javascript">
  $(document).ready(function() {
  
  $("#new_user").validate({
	rules: {
	"user[username]": {required: true},
	"user[firstname]": {required: true},
	"user[lastname]": {required: true},
	"user[email]": {required: true, email: true},  
	"user[password]": {required: true, minlength: 1},
	"password_confirm": {required: true, equalTo: "#user_password"}
	}
	});
  
  $("#user_username").blur(function() {
    //remove all the class add the messagebox classes and start fading
    if ($(this).val()== "")
    {
		$("#msgbox").removeClass().text('').fadeIn("slow");
		return;
    }
    $("#msgbox").removeClass().addClass('messagebox').text('Checking...').fadeIn("slow");
    //check the username exists or not from ajax
    $.post("/checkuser",{ user_username:$(this).val() } ,function(data) {
      if(data=='true') { //if username not avaiable
        $("#msgbox").fadeTo(200,0.1,function() { //start fading the messagebox
          //add message and change the class of the box and start fading
          $(this).html('User name already exists').addClass('messageboxerror').fadeTo(900,1);
        });
        } else {
          $("#msgbox").fadeTo(200,0.1,function() {  //start fading the messagebox
          //add message and change the class of the box and start fading
          $(this).html('User name available to register').addClass('messageboxok').fadeTo(900,1);
        });
      }
    });
  });
});

</script>


<%= form_for(@user) do |f| %>	

<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
	
	
<table width="100%" border="0" cellspacing="0" cellpadding="6">
    <tr><td height="15"></td></tr>
  <tr>
    <td colspan="4"><h2>Add User</h2></td>
    </tr>
    <tr>
    <td height="20"></td>
    </tr>
    <tr>
    <td align="right"class="brown_txt_m"><strong><span class="redstar">*</span> user name</strong></td>
    <td>:</td>
    <td colspan="2" align="left"><%= f.text_field :username, :class=>'textfield_b'%>
     <span id="msgbox" style="display:none"></span>

    
    </td>
    </tr>
  <tr>
    <td width="22%" align="right" valign="middle" class="brown_txt_m"><strong><span class="redstar">*</span> first name</strong></td>
    <td width="2%">:</td>
    <td colspan="2" align="left"><%= f.text_field :firstname, :class=>'textfield_b' %></td>
    </tr>
  <tr>
    <td align="right"class="brown_txt_m"><strong><span class="redstar">*</span> last name</strong></td>
    <td>:</td>
    <td colspan="2" align="left"><%= f.text_field :lastname, :class=>'textfield_b' %></td>
    </tr>
  <tr>
    <td align="right"class="brown_txt_m"><strong><span class="redstar">*</span> email</strong></td>
    <td>:</td>
    <td colspan="2" align="left"><%= f.text_field :email, :class=>'textfield_b' %></td>
    </tr>
  
  <tr>
    <td align="right"class="brown_txt_m"><strong><span class="redstar">*</span>  password</strong></td>
    <td>:</td>
    <td colspan="2" align="left"><%= f.password_field :password, :class=>'textfield_b' %></td>
    </tr>
	<tr>
		<td align="right"class="brown_txt_m">
			<strong>
				<span class="redstar">*</span> Confirm Password
			</strong>
		</td>
		<td>:</td>
		<td colspan="2" align="left">
			<input type="password" id="password_confirm" name="password_confirm"  class="textfield_b"/>
		</td>
	</tr>
	
  
  
  <tr>
    <td align="right" class="brown_txt_m"><strong><span class="redstar">*</span> role</strong></td>
    <td>:</td>
    <td align="left"><%= f.select :role,options_for_select([['administrator', 'administrator'], ['onboarder','onboarder']]) %>
    </td>
    </tr>
   
  <tr>
    <td align="right" class="brown_txt_m"><strong><span class="redstar">*</span> status</strong></td>
    <td>:</td>
    <td align="left">
    <%= f.select :status,options_for_select([['active', 'active'], ['inactive','inactive']]) %>
    </td>
    </tr>
  <tr>
  
   
      
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td colspan="2" align="left">
		 <a class="squarebutton" href="/users" style="margin-left:6px;"  >
			 <span>cancel</span></a> 
		
		
		
			<%= f.submit %>
		</td>
    </tr>
  
      </table>
      
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Firstname:</b>
  <%= @user.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @user.lastname %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Role:</b>
  <%= @user.role %>
</p>

<p>
  <b>Status:</b>
  <%= @user.status %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>